#!/usr/bin/env python
# -*- coding: utf-8 -*-
__una_palabra__ = [u'ano',
                   u'anal',
                   u'babos\w+',
                   u'carajo',
                   u'\w+cabron\w+',
                   u'caca',
                   u'caga\w+',
                   u'ching\w+',
                   u'coger',
                   u'cojer',
                   u'cojon\w+',
                   u'coños?',
                   u'culo\w+',
                   u'culer\w+',
                   u'estupid\w+',
                   u'guey',
                   u'güeyes',
                   u'idiota\w+',
                   u'joto&',
                   u'maldit\w+',
                   u'mamada&',
                   u'mamón',
                   u'mamon\w+',
                   u'maric\wn',
                   u'maricón',
                   u'maricon\w+',
                   u'mierda',
                   u'panocha',
                   u'pendej\w+',
                   u'pinche',
                   u'pucha',
                   u'\w+put\w+',
                   u'verga\w+']
