---
- name: Add Elasticsearch key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present
  
- name: Add Elasticsearch repository
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/1.6/debian stable main'

- name: Install Required Packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - gcc
    - g++
    - gfortran
    - git-core
    - build-essential
    - libxml2-dev
    - libxslt1-dev
    - libopenblas-dev
    - liblapack-dev
    - python-dev
    - python-pip
    - libmysqlclient-dev
    - mysql-client
    - redis-server
    - elasticsearch


- name: Install project source
  git: repo='https://github.com/mxabierto/sara.git' dest=/home/vagrant/sara

- name: Install Python Requirements
  pip: requirements=/home/vagrant/sara/requirements.txt
  
- name: Start redis
  service: name=redis-server state=started
  
- name: Start Elasticsearch
  service: name=elasticsearch state=started
