---
- name: Add Elasticsearch key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present

- name: Add Elasticsearch repository
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/1.6/debian stable main'

- name: Install Required Packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - gcc
    - g++
    - gfortran
    - git-core
    - build-essential
    - libxml2-dev
    - libxslt1-dev
    - libopenblas-dev
    - liblapack-dev
    - python-dev
    - python-pip
    - libmysqlclient-dev
    - mysql-client
    - redis-server
    - openjdk-7-jdk
    - elasticsearch


- name: Install project source
  git: repo='https://github.com/mxabierto/sara.git' dest=/home/vagrant/sara

- name: Install Python Requirements
  pip: requirements=/home/vagrant/sara/requirements.txt

- name: Start redis
  service: name=redis-server state=started

# Configure Elasticsearch Node
- name: Configuring Elasticsearch Node
  template: src=elasticsearch.yml.j2 dest={{ elasticsearch_conf_dir }}/elasticsearch.yml owner={{ elasticsearch_user }} group={{ elasticsearch_group }} mode=0644
  when: elasticsearch_conf_dir is defined

- template: src=elasticsearch.default.j2 dest=/etc/default/elasticsearch owner={{ elasticsearch_user }} group={{ elasticsearch_group }} mode=0644

- file: path={{ elasticsearch_conf_dir }}/logging.yml owner={{ elasticsearch_user }} group={{ elasticsearch_group }} mode=0644

# Register Elasticsearch service to start on boot
- name: Ensure Elasticsearch is started on boot
  service: name=elasticsearch enabled={{ elasticsearch_service_startonboot }} state={{ elasticsearch_service_state }}

- name: Start Elasticsearch
  service: name=elasticsearch state=started

