---
- name: Install Required Packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - gcc
    - g++
    - gfortran
    - git-core
    - build-essential
    - libxml2-dev
    - libxslt1-dev
    - libopenblas-dev
    - liblapack-dev
    - python-dev
    - python-pip
    - libmysqlclient-dev
    - mysql-client


- name: Install project source
  git: repo='https://github.com/mxabierto/sara.git' dest=/home/vagrant/sara

- name: Install Python Requirements
  pip: requirements=/home/vagrant/sara/requirements.txt
